### ISSUE TITLE
Relative Path

### ISSUE THREAD

**Issue by devmoath** [aschmelyun/mdsee#1]
Hi.

I'm wondering do we have a way to handle relative path for images ?

imagine you have this folder:

```text
.
├── README.md
├── img
│   └── figure-1.png
```

and this is the content of `README.md` file:

```markdown
# Test

![image](img/figure-1.png)
```

the result of running `mdsee README.md` will be :

![CleanShot 2565-07-16 at 10 16 53](https://user-images.githubusercontent.com/28797003/179344665-87582313-b43e-4eee-bf44-91b1b8133954.png)

**Comment by aschmelyun** [comment]
Hi @devmoath 

This should be fixed with [this commit](https://github.com/aschmelyun/mdsee/commit/2f220dd723f1d2dadb66fafd5076d1725d9d4441). Try installing the newest version of mdsee and seeing if this resolves your issue!

```
npm install -g mdsee
mdsee README.md
```

**Comment by devmoath** [comment]
yes it is. thank you
